services:
  catalogdb:
    image: mongo
  basketdb:
    image: redis
  discountdb:
    image: postgres 
  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: Services/Basket/Basket.API
      dockerfile: Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: Services/Discount/Discount.API
      dockerfile: Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: Services/Discount/Discount.Grpc
      dockerfile: Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  rabbitmq:
    image: rabbitmq:management-alpine

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:


